import type { CSSProperties } from 'react';

export const ui = {
  page: {
    maxWidth: 1100,
    textAlign: 'left',
  } as CSSProperties,
  pageWide: {
    maxWidth: 1200,
    textAlign: 'left',
  } as CSSProperties,
  card: {
    background: 'var(--ll-surface)',
    border: '1px solid var(--ll-line)',
    borderRadius: 'var(--ll-radius)',
    padding: '1.1rem 1.25rem',
    marginBottom: '1rem',
    boxShadow: 'var(--ll-shadow)',
    textAlign: 'left',
  } as CSSProperties,
  panel: {
    background: 'var(--ll-surface)',
    border: '1px solid var(--ll-line)',
    borderRadius: 'var(--ll-radius)',
    padding: '1.25rem',
    marginBottom: '1.25rem',
    boxShadow: 'var(--ll-shadow)',
  } as CSSProperties,
  btn: {
    background: 'var(--ll-brand-dark)',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    padding: '0.55rem 0.95rem',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: '0.88rem',
  } as CSSProperties,
  btnGhost: {
    background: 'transparent',
    color: 'var(--ll-brand-dark)',
    border: '1px solid var(--ll-line)',
    borderRadius: 10,
    padding: '0.55rem 0.95rem',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: '0.88rem',
  } as CSSProperties,
  btnDanger: {
    background: 'var(--ll-danger)',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    padding: '0.55rem 0.95rem',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: '0.88rem',
  } as CSSProperties,
  btnSm: {
    padding: '0.4rem 0.7rem',
    fontSize: '0.8rem',
  } as CSSProperties,
  input: {
    width: '100%',
    padding: '0.65rem 0.75rem',
    borderRadius: 10,
    border: '1px solid var(--ll-line)',
    marginTop: 4,
    marginBottom: 12,
    background: '#fff',
    color: 'var(--ll-ink)',
  } as CSSProperties,
  muted: { color: 'var(--ll-muted)' } as CSSProperties,
  row: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    alignItems: 'center',
  } as CSSProperties,
  grid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '0.85rem',
  } as CSSProperties,
  alert: {
    background: 'var(--ll-brand-soft)',
    border: '1px solid #99f6e4',
    color: 'var(--ll-brand-dark)',
    borderRadius: 10,
    padding: '0.85rem 1rem',
    marginBottom: '1rem',
    fontSize: '0.9rem',
  } as CSSProperties,
  alertWarn: {
    background: '#fff7ed',
    border: '1px solid #fed7aa',
    color: '#9a3412',
    borderRadius: 10,
    padding: '0.85rem 1rem',
    marginBottom: '1rem',
    fontSize: '0.9rem',
  } as CSSProperties,
};
